# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MyEthereumWallet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyEthereumWallet
#	pod 'Geth', '1.6.2-unstable.9825'
    pod 'Alamofire', '4.4.0'
end
